//
// Departure.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Departure: Codable {

    public var name: String
    public var stopArea: StopArea
    public var departureTime: Date
    public var type: String?
    public var shortName: String
    /** Minutes until departure */
    public var departsInMinutes: Int
    public var arrivalTime: Date
    public var destination: Destination?

    public init(name: String, stopArea: StopArea, departureTime: Date, type: String?, shortName: String, departsInMinutes: Int, arrivalTime: Date, destination: Destination?) {
        self.name = name
        self.stopArea = stopArea
        self.departureTime = departureTime
        self.type = type
        self.shortName = shortName
        self.departsInMinutes = departsInMinutes
        self.arrivalTime = arrivalTime
        self.destination = destination
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case stopArea = "StopArea"
        case departureTime = "DepartureTime"
        case type = "Type"
        case shortName = "ShortName"
        case departsInMinutes = "DepartsInMinutes"
        case arrivalTime = "ArrivalTime"
        case destination = "Destination"
    }


}

