//
// ParkingArea.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ParkingArea: Codable {

    /** Departures from the parking area, sorted by minutes until departure */
    public var departures: [Departure]?
    public var name: String
    public var stopAreas: [StopArea]
    public var _id: Int64
    public var parkingLots: [ParkingLot]

    public init(departures: [Departure]?, name: String, stopAreas: [StopArea], _id: Int64, parkingLots: [ParkingLot]) {
        self.departures = departures
        self.name = name
        self.stopAreas = stopAreas
        self._id = _id
        self.parkingLots = parkingLots
    }

    public enum CodingKeys: String, CodingKey { 
        case departures = "Departures"
        case name = "Name"
        case stopAreas = "StopAreas"
        case _id = "Id"
        case parkingLots = "ParkingLots"
    }


}

