//
// StopArea.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StopArea: Codable {

    public var name: String
    public var municipality: String
    public var gid: Int64

    public init(name: String, municipality: String, gid: Int64) {
        self.name = name
        self.municipality = municipality
        self.gid = gid
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case municipality = "Municipality"
        case gid = "Gid"
    }


}

